Added Transcript Data Interface
BestFloww/BestFlow pull request #27
Opened 2022-10-23 20:32 UTC by williamyao27

## Pull Request Summary
Added TranscriptDataInterface and modified TranscriptDataFormatter and TranscriptController accordingly for CA.

### Change types
- [x] Non-breaking change
- [x] Adding to API

### Testing
N/A

### How to manually test this PR (QA instructions)
Verify that the interface still formats the transcript properly.

## Questions
Wasn't too sure of how the interface should work so I just followed intent-interface. I was wondering why in intentdao, the params and return are only indicated for the first implemented method instead of all of them?

2022-10-23 20:48 UTC, WeissSa requested changes
99% of the way there. Remember to actively set the dataformatter in the route (like we did on Friday with the intentDao. I don't think that change went live so to recap:
```
routerFunction((req, res, next) => {
  TranscriptController.setIntentDao(IntentDao)
  TranscriptController.setTranscriptFormatter(TranscriptDataFormatter)
  TranscriptController.post(req, res, next)
})
```
)

2022-10-23 20:48 UTC, WeissSa commented on back-end/helpers/transcript_data_formatter.js
> +     * */
The Javadoc can go in the interface to reduce clutter

2022-10-24 00:50 UTC, WeissSa approved these changes
LGTM 👍

2022-10-24 21:54 UTC, helias22 approved these changes

2022-10-24 22:53 UTC, merged