Add comments for transcript formatter
BestFloww/BestFlow pull request #34
Opened 2022-10-24 23:43 UTC by helias22

## Pull Request Summary

### Change types

- [x] Non-breaking change

### Testing
- [ ] I have added testing to this PR 

### How to manually test this PR (QA instructions)

## Questions

2022-10-24 23:45 UTC, KayleeLChan approved these changes
mmm spicy communication in the code it's too good. 💃 💃 💃

2022-10-25 00:01 UTC, WeissSa requested changes
Some small changes would be good. TY for commenting this!

2022-10-25 00:01 UTC, WeissSa commented on front-end/package-lock.json
> -        "minimatch": ">=3.0.5",
We should not be removing this.

2022-10-25 16:44 UTC, WeissSa approved these changes
Great changes!

2022-10-25 18:08 UTC, merged