Formatting for Display
BestFloww/BestFlow pull request #80
Opened 2022-11-17 20:17 UTC by emilylwan

## Pull Request Summary

Parse the displayed text to get rid of voice name and fixed issues with not replacing -DOT- with .

### Change types

- [x] Non-breaking change

### Testing

### How to manually test this PR (QA instructions)
Upload a transcript and check that the text formatting has periods and that voice name is replaced with just the name.

## Questions

2022-11-17 20:18 UTC, WeissSa requested changes
Small testing things (as is my usual), but overall really good

2022-11-17 20:18 UTC, WeissSa commented on back-end/helpers/intent_analyzer.js
> +      question: model.question.replaceAll("-DOT-", "."),
good catch. Maybe add a test so this doesn't happen again in future (

2022-11-17 20:18 UTC, WeissSa commented on back-end/helpers/intent_analyzer.js
> +        const replacedIntent = intent.replaceAll("-DOT-", ".")
+1

2022-11-17 20:18 UTC, WeissSa commented on back-end/helpers/transcript_data_formatter.js
> +            }
Maybe add this to the description of a test so it is explicit

2022-11-17 20:26 UTC, WeissSa approved these changes
Awesome :sunglasses:

2022-11-18 01:55 UTC, helias22 reviewed
Great catch on the multiple dots problem. I also saw that today in the presentation and I wanted to add another ticket to solve it :)
About getting rid of the voice I don't think It's completely clean yet. This is what I get when I try it with my sample transcript.
<img width="579" alt="Screen Shot 2022-11-17 at 8 46 59 PM" src="https://user-images.githubusercontent.com/98133719/202598851-05ad2431-5fb9-4592-a79d-f05910a7e6d0.png">

2022-11-18 14:30 UTC, emilylwan commented
@helias22 I found the problem and hopefully fixed it. Let me know if it works now. Though also on another note, are there going to be quotations around the main message in transcripts? From what I can see on the data Denys sent us, he didn't put quotes around the text.

2022-11-18 20:33 UTC, helias22 approved these changes
Yes the problem is solved. About the quotations, I think I accidentally added those when I was adding to the transcript. Great catch :))

2022-11-18 21:26 UTC, williamyao27 approved these changes
LGTM!

2022-11-18 22:08 UTC, merged