styling changes for other screen sizes
BestFloww/BestFlow pull request #94
Opened 2022-11-24 17:56 UTC by WeissSa

## Pull Request Summary
I added breakpoints and other styling changes for other screen sizes. Most notable change is a reposition the percentage of each leaf so it is fixed at the top. 

### Change types

- [x] Non-breaking change
- [x] Front end change

### How to manually test this PR (QA instructions)
Check the netlify portal and resize ur window

## Questions

Very open to design ideas :grin:

2022-11-24 18:54 UTC, helias22 reviewed
Everything looks fine to me. It's just that this input field seems a little off.
<img width="1440" alt="Screen Shot 2022-11-24 at 1 51 30 PM" src="https://user-images.githubusercontent.com/98133719/203850475-a0d82a9b-cdd4-4f43-aea8-d27b92faa60f.png">

2022-11-24 19:06 UTC, WeissSa commented
@helias22 good catch. Fixed!

2022-11-24 22:05 UTC, KayleeLChan requested changes
Awesome work on grinding out the Tailwind to make the view a lot better, I just had some things I noticed, I'd love to get some input from others to figure out whether it's just me who's having these issues or if they have them as well:

![image](https://user-images.githubusercontent.com/82854864/203867316-d4d868cf-7bea-42a6-99af-0df82b5b098f.png)

Could we have this button resized so that the padding isn't too large?

![image](https://user-images.githubusercontent.com/82854864/203868228-a665ad1d-6549-4f3a-ba48-f5188e963ff6.png)

There's also massive scrolling space for some reason, is this just me?

2022-11-24 22:05 UTC, KayleeLChan commented on front-end/src/components/main-page/MainPage.jsx
>                  click={this.toggleTranscriptUploadModal}
I'm thinking we could also resize the modal a bit so that the Drag and drop line doesn't have to go into two lines

2022-11-24 23:17 UTC, WeissSa commented on front-end/src/components/main-page/MainPage.jsx
> +                    size: "40"
It's the same in normal view

2022-11-24 23:18 UTC, WeissSa commented on front-end/src/components/main-page/MainPage.jsx
>                  click={this.toggleTranscriptUploadModal}
This works for me on my version. How did u emulate mobile view on your PC?

2022-11-24 23:31 UTC, WeissSa commented on front-end/src/components/analysis-page/AnalysisPage.jsx
>                <div className= "w-full bg-gray-100 pb-2">
Cannot replicate this. Maybe try again on my push.

2022-11-24 23:31 UTC, WeissSa commented on front-end/src/components/analysis-page/IntentMenu.jsx
> +                className={"z-10 w-full sm:w-1/3 lg:w-1/4 h-full bg-off-white font-cabin fixed sm:absolute shadow-lg shadow-blue/30 transition ease-in-out " + (this.props.isOpen ? "translate-x-0" : "
Again I cannot replicate this. Try on next push.

2022-11-25 01:50 UTC, KayleeLChan commented on front-end/src/components/main-page/MainPage.jsx
>                  click={this.toggleTranscriptUploadModal}
After the latest push, it's working now, don't know what it might've been lol but at least it's all good

2022-11-25 01:54 UTC, WeissSa commented on front-end/src/components/main-page/MainPage.jsx
>                  click={this.toggleTranscriptUploadModal}
pog!

2022-11-25 02:00 UTC, KayleeLChan approved these changes
All the changes look good to me! Love how it works nice and cleanly now! 💃 💃 💃

2022-11-26 03:52 UTC, williamyao27 approved these changes
Code LGTM. I QA'd at your place earlier and it was good then too. Great changes!

2022-11-26 03:53 UTC, merged